In [ ]:
import pandas as pd
df=pd.read_csv("internship_project.csv")
df.head(7)

,EmployeeID,Department,Age,Gender,ExperienceYears,SalaryBand,MonthlySalary,JobSatisfaction,WorkLifeBalance,Overtime,Attrition
0,E1000,IT,39,Male,14,High,124255,5,3,Yes,Yes
1,E1001,Operations,41,Female,11,Medium,78226,4,5,No,No
2,E1002,Finance,37,Male,15,Low,26079,4,4,Yes,Yes
3,E1003,IT,43,Male,18,Medium,52454,1,4,Yes,Yes
4,E1004,Sales,32,Male,7,Low,38814,5,4,No,No
5,E1005,Sales,42,Female,20,Medium,58264,1,2,No,No
6,E1006,HR,41,Male,16,Medium,52159,5,5,No,No

In [ ]:
df.tail()

,EmployeeID,Department,Age,Gender,ExperienceYears,SalaryBand,MonthlySalary,JobSatisfaction,WorkLifeBalance,Overtime,Attrition
995,E1995,HR,37,Male,9,Medium,72093,3,4,Yes,No
996,E1996,Operations,34,Female,6,Medium,51411,1,4,Yes,No
997,E1997,Sales,29,Male,4,Low,39522,5,3,Yes,Yes
998,E1998,Operations,29,Male,0,Low,29095,2,5,No,No
999,E1999,IT,33,Female,12,High,100471,3,1,No,No