In [ ]:
import pandas as pd
df=pd.read_csv("internship_project.csv")
df.head(7)

,EmployeeID,Department,Age,Gender,ExperienceYears,SalaryBand,MonthlySalary,JobSatisfaction,WorkLifeBalance,Overtime,Attrition
0,E1000,IT,39,Male,14,High,124255,5,3,Yes,Yes
1,E1001,Operations,41,Female,11,Medium,78226,4,5,No,No
2,E1002,Finance,37,Male,15,Low,26079,4,4,Yes,Yes
3,E1003,IT,43,Male,18,Medium,52454,1,4,Yes,Yes
4,E1004,Sales,32,Male,7,Low,38814,5,4,No,No
5,E1005,Sales,42,Female,20,Medium,58264,1,2,No,No
6,E1006,HR,41,Male,16,Medium,52159,5,5,No,No

In [ ]:
import pandas as pd
df = pd.read_csv("internship_project.csv")
df.tail()

,EmployeeID,Department,Age,Gender,ExperienceYears,SalaryBand,MonthlySalary,JobSatisfaction,WorkLifeBalance,Overtime,Attrition
995,E1995,HR,37,Male,9,Medium,72093,3,4,Yes,No
996,E1996,Operations,34,Female,6,Medium,51411,1,4,Yes,No
997,E1997,Sales,29,Male,4,Low,39522,5,3,Yes,Yes
998,E1998,Operations,29,Male,0,Low,29095,2,5,No,No
999,E1999,IT,33,Female,12,High,100471,3,1,No,No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EmployeeID       1000 non-null   object
 1   Department       1000 non-null   object
 2   Age              1000 non-null   int64
 3   Gender           1000 non-null   object
 4   ExperienceYears  1000 non-null   int64
 5   SalaryBand       1000 non-null   object
 6   MonthlySalary    1000 non-null   int64
 7   JobSatisfaction  1000 non-null   int64
 8   WorkLifeBalance  1000 non-null   int64
 9   Overtime         1000 non-null   object
 10  Attrition        1000 non-null   object
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

In [ ]:

df.describe()

,Age,ExperienceYears,MonthlySalary,JobSatisfaction,WorkLifeBalance
count,1000.000000,1000.00000,1000.00000,1000.000000,1000.000000
mean,35.244000,9.81700,60212.92300,2.977000,2.948000
std,6.548844,6.00046,32595.14073,1.401583,1.416793
min,21.000000,0.00000,20016.00000,1.000000,1.000000
25%,30.000000,5.00000,34245.50000,2.000000,2.000000
50%,35.000000,10.00000,52386.00000,3.000000,3.000000
75%,40.000000,15.00000,74762.00000,4.000000,4.000000
max,50.000000,20.00000,149923.00000,5.000000,5.000000

In [ ]:
df.columns

Index(['EmployeeID', 'Department', 'Age', 'Gender', 'ExperienceYears',
       'SalaryBand', 'MonthlySalary', 'JobSatisfaction', 'WorkLifeBalance',
       'Overtime', 'Attrition'],
      dtype='object')